algoritmo "semnome"
// Função : Fazer a aplicação receber nome idade e repetir 10 vezes no terminal
// Autor :  Alex Miranda
// Data : 27/04/2017
// Seção de Declarações 
var
   nome : caractere
   idade, cont : real
inicio
   nome <- ("Alex Miranda da Silva")
   idade <- 30
   cont<-1
   enquanto   (cont <=10) faca

   cont <- cont + 1
   escreval (nome, ", tenho ",30," anos.")
   fimenquanto
fimalgoritmo
